[package]
name = "myaso-server"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
publish = false
license = "Apache-2.0"

[dependencies]
anyhow = "=1.0.104"
tokio = { version = "~1.51", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
wtransport = { version = "=0.7.2", default-features = false, features = ["ring", "self-signed"] }

[dev-dependencies]
